# Display Changelog Summary
# Shows what's being released in the GitHub Actions job summary

name: Changelog Summary

on:
  pull_request:
    branches:
      - production

permissions:
  contents: read

jobs:
  changelog:
    name: Show Release Changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Generate Changelog Summary
        run: |
          echo "## 📋 Release Changelog" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          # Extract changelogs for packages being released
          for changelog in packages/*/CHANGELOG.md packages/connectors/*/CHANGELOG.md; do
            if [ -f "$changelog" ]; then
              pkg_name=$(echo "$changelog" | sed 's|.*/\([^/]*\)/CHANGELOG.md|\1|')
              
              # Extract first entry (between first two ## headers)
              first_entry=$(awk '/^## / {if (++count == 2) exit} count == 1' "$changelog")
              
              if [ -n "$first_entry" ]; then
                echo "### 📦 $pkg_name" >> $GITHUB_STEP_SUMMARY
                echo "$first_entry" >> $GITHUB_STEP_SUMMARY
                echo "" >> $GITHUB_STEP_SUMMARY
              fi
            fi
          done
