# CI for Release Branch
# Runs comprehensive checks on all packages in the release-next branch

name: Check Release before publish
on:
  pull_request_target:
    branches:
      - production

permissions:
  actions: read
  contents: read

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE_KEY }}

  ci-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v5
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install --no-package-lock

      - name: Build tools
        run: npm run build

      - name: Format check
        run: npx nx format:check || true

      - name: Run full CI on all release packages
        run: |
          echo "Running comprehensive CI on all packages..."
          npx nx run-many -t lint test build typecheck --projects='packages/*,packages/connectors/*'

      - name: Fix CI issues
        if: failure()
        run: npx nx fix-ci || true
