# CI for Release Branch
# Runs comprehensive checks on all packages in the release-next branch

name: Check Release before publish
on:
  pull_request_target:
    branches:
      - production

permissions:
  actions: read
  contents: read

jobs:
  ci-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v5
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install --no-package-lock

      - name: Build tools
        run: npm run build

      - name: Format check
        run: npx nx format:check || true

      - name: Generate Changelog Summary
        run: |
          echo "## 📋 Release Changelog" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          # Extract changelogs for packages being released
          for changelog in packages/*/CHANGELOG.md packages/connectors/*/CHANGELOG.md; do
            if [ -f "$changelog" ]; then
              pkg_name=$(echo "$changelog" | sed 's|.*/\([^/]*\)/CHANGELOG.md|\1|')
              
              # Extract first entry (between first two ## headers)
              first_entry=$(awk '/^## / {if (++count == 2) exit} count == 1' "$changelog")
              
              if [ -n "$first_entry" ]; then
                echo "### 📦 $pkg_name" >> $GITHUB_STEP_SUMMARY
                echo "$first_entry" >> $GITHUB_STEP_SUMMARY
                echo "" >> $GITHUB_STEP_SUMMARY
              fi
            fi
          done

      - name: Run full CI on all release packages
        run: |
          echo "Running comprehensive CI on all packages..."
          npx nx run-many -t lint test build typecheck --projects='packages/*,packages/connectors/*'

      - name: Fix CI issues
        if: failure()
        run: npx nx fix-ci || true
